# **Lab 08: Quadratic Programing using `qpsolver` and `gurobipy`**

**By N. Hemachandra and R. Deval**

### **Objective:** In **Lab08** we will perform optimization for a quadratic programs.


# **Quadratic Program**

Formulation of the type

$$\begin{align*}
    \min_{x}: & \frac{1}{2}x^TPx + q^T x +s \\
    \textit{subject to}: \\
    & Gx \leq h \\
    & Ax = b \\
   l \leq & x \leq u\\
\end{align*}
$$

is known as a ***quadratic program*** with linear constraints due to quadratic nature of objective function. This particular class of problem are known as non-linear problem but are convex in nature. So, any local minima will be an eventual global minima for problem. \\

$x = \big[ x_1, x_2, \cdots x_n \big]$ is vector of decision variables. Further, $P$ is a positive (semi) definite matrix interpreted as coefficient of quadratic cost, $q$ is a vector of linear cost. $G$ is a matrix of coefficient of constraints and $h$ is vector of constraint capacity bounds. Similarly, $A$ and $b$ are matrix and vector representation of system affline constrants. Here, $l$ and $u$ are bounds on decision variable $x$.

Use the `qpsolvers` library to solve quadratic programs and any further help [Click Here](https://pypi.org/project/qpsolvers/) \\

Consider following problem:

$$\begin{align*}
    \min_{x} f(x): & \frac{1}{2} x_1^2 + x_2^2 - x_1 x_2 - 2x_1 - 6x_2\\
    \textit{subject to}: \\
     x_1 + x_2 & \leq 2 \\
     -x_1 + 2x_2 & \leq 2 \\
     2x_1 + x_2 & \leq 3 \\
     x_1 + x_2 & = \frac{1}{2} \\
     x_1, x_2 & \geq 0\\
    x_1, x_2 & \leq 1\\
\end{align*}
$$


Rewrite above equation in matrix notation and use below ready to made code in order to solve above optimization problem. You need to identify, $P$, $q$, $s$, $G$, $h$, $A$ $b$, $l$, $u$ from above given system.

Below is detailed description about how to use a quadratic optimization solver. We will be using `qpsolvers` for its simplicity in optimizing quadratic programs.

```python
# installing qpsolvers from web
!pip -q install qpsolvers[open_source_solvers]
from qpsolvers import solve_qp
import numpy as np
```

In [1]:
# installing qpsolvers from web
!pip -q install qpsolvers[open_source_solvers]
from qpsolvers import solve_qp
import numpy as np

clearly the for the problem above, the P and Q are
$$P =  \begin{bmatrix}
1 & -1 \\
-1 & 2
\end{bmatrix}  $$
 and
 $$q =  \begin{bmatrix}
-2 & -6
\end{bmatrix} ^T $$
subject to
$$G =  \begin{bmatrix}
1& 1 \\
-1 & 2 \\
 2 & 1
\end{bmatrix}  $$
and
$$h=\begin{bmatrix}
2 \\
2 \\
3
\end{bmatrix},s=0$$
and
$$A =  \begin{bmatrix}
1 & 1
\end{bmatrix}
$$
and b = 1/2 and lb = 0 , ub = 1

Once you install your and import all necessary libraries, you need identify $P$, $q$, $s$, $G$, $h$, $A$ $b$, $l$, and $u$  to represent above mathematical formulation into matrix notations.

```python
# P represents quadratic cost coefficients
P = np.array([[]])
# q represents linear cost coefficients
q = np.array([]) # it will be an array
```

In [2]:
# P represents quadratic cost coefficients
P = np.array([[1,-1],[-1,2]])
# q represents linear cost coefficients
q = np.array([-2,-6]) # it will be an array

```python
# G matrix representation of coefficients of inequality constraints
G = np.array([[]])
# h vector representation of capacity bounds for inequality constraints
h = np.array([]) # it will be an array
```

In [3]:
# G matrix representation of coefficients of inequality constraints
G = np.array([[1,1],[-1,2],[2,1]])
# h vector representation of capacity bounds for inequality constraints
h = np.array([2,2,3]) # it will be an array

Try solving your optimization problem as of now with only objective function and inequaility constraints with following snip to code

``` python
solve_qp(P, q, G, h, A, b, l, u, solver = "osqp")
```

By default it `solve_qp` uses 8 argument along with solver type. For now to solve initially use following:

``` python
solve_qp(P, q, G, h, A = None, b =None, l=None, u=None, solver = "osqp")
```


In [4]:
solve_qp(P, q, G, h, A = None, b =None, lb=None, ub=None, solver = "osqp")

/usr/local/lib/python3.10/dist-packages/qpsolvers/conversions/ensure_sparse_matrices.py:38: UserWarning: Converted P to scipy.sparse.csc.csc_matrix
For best performance, build P as a scipy.sparse.csc_matrix rather than as a numpy.ndarray
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/qpsolvers/conversions/ensure_sparse_matrices.py:38: UserWarning: Converted G to scipy.sparse.csc.csc_matrix
For best performance, build G as a scipy.sparse.csc_matrix rather than as a numpy.ndarray
  warnings.warn(


array([0.66650027, 1.33321806])

Add the equaility constaint to solve above formulation as

```python
# an array of an array to represent matrix to represent coefficient of constraints with equaility type.
A = np.array([[]])
# a vector to represent RHS of equality constraints
b = np.array([])

# now solve above formulation as
solve_qp(P, q, G, h, A, b, None, None, sovler="osqp")
```


In [5]:
# an array of an array to represent matrix to represent coefficient of constraints with equaility type.
A = np.array([[1,1]])
# a vector to represent RHS of equality constraints
b = np.array([0.5])

# now solve above formulation as
solve_qp(P, q, G, h, A, b, None, None, solver="osqp")

/usr/local/lib/python3.10/dist-packages/qpsolvers/conversions/ensure_sparse_matrices.py:38: UserWarning: Converted A to scipy.sparse.csc.csc_matrix
For best performance, build A as a scipy.sparse.csc_matrix rather than as a numpy.ndarray
  warnings.warn(


array([-0.3332799 ,  0.83323339])

At last you can define bounds on decision variables and solve quadratic program for optimality using following snip

```python
l = np.array([])
u = np.array([])

# solve for optimality as
x= solve_qp(P, q, G, h, A, b, l, u, sovler = "osqp"

```

In [6]:
l = np.array([0,0])
u = np.array([1,1])

# solve for optimality as
x= solve_qp(P, q, G, h, A, b, l, u, solver = "osqp")

In [7]:
x

array([-4.54106735e-04,  5.00430952e-01])

In [8]:
0.5*x@P@x + q@x

-2.7510190084405086

# **Using Gurobi solver for optimization**

`Gurobi` is one of the widely used optimization solver used commercially in the industry which provides interface to solve  linear programming (LP), quadratic programming (QP), quadratically constrained programming (QCP), mixed integer linear programming (MILP), mixed-integer quadratic programming (MIQP), and mixed-integer quadratically constrained programming (MIQCP).

**Note**: `Gurobi` also provide interface to solve non-convex optimization problems.

Below is a short tutorial to perform computational optimization using Gurobi, assuming that we will be solving the above quadratic problem with $P, q, G, h, A, b, l, u$ as above defined user-inputs

### **Step 1: Install Gurobi from web**

```python
# this api will help to install gurobi library on your cloud
!pip install -i https://pypi.gurobi.com gurobipy
```

In [9]:
# this api will help to install gurobi library on your cloud
!pip install -i https://pypi.gurobi.com gurobipy

Looking in indexes: https://pypi.gurobi.com


### **Step 2: Import Gurobi library**

```python
# we can import gurobi in our session using following library, remember gurobipy is used to import library
import gurobipy as gp
```

In [10]:
import gurobipy as gp

### **Step 3: Defining model strucutre for gurobi**

```python
# below is a standard snip to code which we can follow to define model structure using gurobi

# below we create an empty model
model = gp.Model()

# following command is optimal where we reset our existing model
model.reset(0)

# decision variables for optimization can be defined as follows
n=2
x = model.addMVar(n)
# above n is the number of decision variables used

# standard procedure to define objective function where @ is used for matrix/vector multiplication with matrix/vector by default it takes minimization as sense of optimization
model.setObjective((1/2)*x @ P @ x + q @ x)

# below we define inequality constraint as
model.addConstr(G @ x <=h)

# finallay equaility constraints can be defined as
model.addConstr(A @ x == b)

# boundary constraints can be defined as
model.addConstr( x <= u)
model.addConstr( x >= l)

```

In [11]:
# below is a standard snip to code which we can follow to define model structure using gurobi

# below we create an empty model
model = gp.Model()

# following command is optimal where we reset our existing model
model.reset(0)

# decision variables for optimization can be defined as follows
n=2
x = model.addMVar(n)
# above n is the number of decision variables used

# standard procedure to define objective function where @ is used for matrix/vector multiplication with matrix/vector by default it takes minimization as sense of optimization
model.setObjective((1/2)*x @ P @ x + q @ x)

# below we define inequality constraint as
model.addConstr(G @ x <=h)

# finallay equaility constraints can be defined as
model.addConstr(A @ x == b)

# boundary constraints can be defined as
model.addConstr( x <= u)
model.addConstr( x >= l)

Restricted license - for non-production use only - expires 2024-10-28
Discarded solution information


<MConstr (2,) *awaiting model update*>

### **Step 4: Updating model and solving system**

```python
# before solving you need to update all the exisiting information about constraints and objective to model as
model.update()


# you can display your formulation as
model.display()


# you can optimize your model below as
model.optimize()

```

In [12]:
# before solving you need to update all the exisiting information about constraints and objective to model as
model.update()


# you can display your formulation as
model.display()


# you can optimize your model below as
model.optimize()

Minimize
  -2.0 C0 + -6.0 C1 + [ 0.5 C0 ^ 2 + -1.0 C0 * C1 + C1 ^ 2 ]
Subject To
  R0: C0 + C1 <= 2
  R1: -1.0 C0 + 2.0 C1 <= 2
  R2: 2.0 C0 + C1 <= 3
  R3: C0 + C1 = 0.5
  R4: C0 <= 1
  R5: C1 <= 1
  R6: C0 >= -0
  R7: C1 >= -0
Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (linux64)

CPU model: Intel(R) Xeon(R) CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads

Optimize a model with 8 rows, 2 columns and 12 nonzeros
Model fingerprint: 0x17adfa50
Model has 3 quadratic objective terms
Coefficient statistics:
  Matrix range     [1e+00, 2e+00]
  Objective range  [2e+00, 6e+00]
  QObjective range [1e+00, 2e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [5e-01, 3e+00]
Presolve removed 7 rows and 0 columns
Presolve time: 0.01s
Presolved: 1 rows, 2 columns, 2 nonzeros
Presolved model has 3 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 Free vars  : 1
 AA' NZ     : 1.000e+00
 Factor NZ 

### **Step 5: Display your solution**

```python
# once you have optimized your formulation, you can look display your optimal values as

optimal_values = model.x

optimal_values
```

In [13]:
optimal_values = model.x

optimal_values

[2.3872858666062987e-09, 0.4999999976127142]